[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-dl-project"
version = "0.1.0"
description = "EEG motor imagery classification project for DSCI 410/510."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "torchvision",
    "PyYAML",
    "mne",
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "jupyter"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]